/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { default as AboutRouteComponent } from './routes/about.mdx'
import { default as BlogIndexRouteComponent } from './routes/blog.index.mdx'
import { default as PostsPostIdRouteComponent } from './routes/posts.$postId.mdx'
import { default as marketingPricingRouteComponent } from './routes/(marketing)/pricing.mdx'
import { default as DocsLayoutGettingStartedRouteComponent } from './routes/docs/_layout/getting-started.mdx'
import { default as DocsLayoutApiReferenceRouteComponent } from './routes/docs/_layout/api-reference.mdx'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsLayoutRouteImport } from './routes/docs/_layout'

const DocsRouteImport = createFileRoute('/docs')()
const AboutRouteImport = createFileRoute('/about')()
const BlogIndexRouteImport = createFileRoute('/blog/')()
const PostsPostIdRouteImport = createFileRoute('/posts/$postId')()
const marketingPricingRouteImport = createFileRoute('/(marketing)/pricing')()
const DocsLayoutGettingStartedRouteImport = createFileRoute(
  '/docs/_layout/getting-started',
)()
const DocsLayoutApiReferenceRouteImport = createFileRoute(
  '/docs/_layout/api-reference',
)()

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).update({ component: AboutRouteComponent })
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any).update({ component: BlogIndexRouteComponent })
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any).update({ component: PostsPostIdRouteComponent })
const DocsLayoutRoute = DocsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DocsRoute,
} as any)
const marketingPricingRoute = marketingPricingRouteImport
  .update({
    id: '/(marketing)/pricing',
    path: '/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({ component: marketingPricingRouteComponent })
const DocsLayoutGettingStartedRoute =
  DocsLayoutGettingStartedRouteImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => DocsLayoutRoute,
  } as any).update({ component: DocsLayoutGettingStartedRouteComponent })
const DocsLayoutApiReferenceRoute = DocsLayoutApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DocsLayoutRoute,
} as any).update({ component: DocsLayoutApiReferenceRouteComponent })

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof marketingPricingRoute
  '/docs': typeof DocsLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/blog': typeof BlogIndexRoute
  '/docs/api-reference': typeof DocsLayoutApiReferenceRoute
  '/docs/getting-started': typeof DocsLayoutGettingStartedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof marketingPricingRoute
  '/docs': typeof DocsLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/blog': typeof BlogIndexRoute
  '/docs/api-reference': typeof DocsLayoutApiReferenceRoute
  '/docs/getting-started': typeof DocsLayoutGettingStartedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/(marketing)/pricing': typeof marketingPricingRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/_layout': typeof DocsLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/_layout/api-reference': typeof DocsLayoutApiReferenceRoute
  '/docs/_layout/getting-started': typeof DocsLayoutGettingStartedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/docs'
    | '/posts/$postId'
    | '/blog'
    | '/docs/api-reference'
    | '/docs/getting-started'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/docs'
    | '/posts/$postId'
    | '/blog'
    | '/docs/api-reference'
    | '/docs/getting-started'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/(marketing)/pricing'
    | '/docs'
    | '/docs/_layout'
    | '/posts/$postId'
    | '/blog/'
    | '/docs/_layout/api-reference'
    | '/docs/_layout/getting-started'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  marketingPricingRoute: typeof marketingPricingRoute
  DocsRoute: typeof DocsRouteWithChildren
  PostsPostIdRoute: typeof PostsPostIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/_layout': {
      id: '/docs/_layout'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsLayoutRouteImport
      parentRoute: typeof DocsRoute
    }
    '/(marketing)/pricing': {
      id: '/(marketing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/_layout/getting-started': {
      id: '/docs/_layout/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsLayoutGettingStartedRouteImport
      parentRoute: typeof DocsLayoutRoute
    }
    '/docs/_layout/api-reference': {
      id: '/docs/_layout/api-reference'
      path: '/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsLayoutApiReferenceRouteImport
      parentRoute: typeof DocsLayoutRoute
    }
  }
}

interface DocsLayoutRouteChildren {
  DocsLayoutApiReferenceRoute: typeof DocsLayoutApiReferenceRoute
  DocsLayoutGettingStartedRoute: typeof DocsLayoutGettingStartedRoute
}

const DocsLayoutRouteChildren: DocsLayoutRouteChildren = {
  DocsLayoutApiReferenceRoute: DocsLayoutApiReferenceRoute,
  DocsLayoutGettingStartedRoute: DocsLayoutGettingStartedRoute,
}

const DocsLayoutRouteWithChildren = DocsLayoutRoute._addFileChildren(
  DocsLayoutRouteChildren,
)

interface DocsRouteChildren {
  DocsLayoutRoute: typeof DocsLayoutRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsLayoutRoute: DocsLayoutRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  marketingPricingRoute: marketingPricingRoute,
  DocsRoute: DocsRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
